[[redirects]]
    from = "https://vellip.de/*"
    to = "https://vellip.berlin/:splat"
    force = true

[[redirects]]
    from = "https://vellip-portfolio.netlify.app/*"
    to = "https://vellip.berlin/:splat"
    force = true
